OpenStack works\!

diff --git a/postscripts/setupCeph b/postscripts/setupCeph
--- a/postscripts/setupCeph
+++ b/postscripts/setupCeph
@@ -12,7 +12,10 @@ function nodeNameToNumber {
 }
 
 #This ought to make all output go to syslog?
-exec >(logger -t cephSetup[$$])
+#exec >(logger -t cephSetup[$$])
+
+# Verify the path is as dumb as I think
+log Path is $PATH
 
 # Gather the bit of data we'll need...
 NODENUM=$(( $(nodeNameToNumber `hostname` ) - 1 ))
@@ -38,7 +41,7 @@ then
 	log Unmounted /dev/sda3
 else
 	log Unmounting /dev/sda3 failed:
-	#log `umount /dev/sda3`
+	log `umount /dev/sda3`
 fi
 
 mkfs -t btrfs -L ceph /dev/sda3
@@ -47,7 +50,7 @@ then
 	log Made btrfs
 else
 	log Failed ot make btrfs!
-	#log `mkfs -t btrfs -L ceph /dev/sda3`
+	log `mkfs -t btrfs -L ceph /dev/sda3`
 	exit 2
 fi
 
@@ -58,7 +61,7 @@ then
 	log made "/var/lib/ceph/osd/ceph-${NODENUM}"
 else
 	log Failed to make OSD data dir
-	#log `mkdir -p "/var/lib/ceph/osd/ceph-${NODENUM}"`
+	log `mkdir -p "/var/lib/ceph/osd/ceph-${NODENUM}"`
 	exit 3
 fi
 
@@ -69,19 +72,20 @@ then
 	log Mounted btrfs disk...
 else
 	log Failed ot mount btrfs.  Bailing.
-	#log `mount LABEL=ceph "/var/lib/ceph/osd/ceph-${NODENUM}"`
+	log `mount LABEL=ceph "/var/lib/ceph/osd/ceph-${NODENUM}"`
 	exit 4
 fi
 
 #from http://ceph.com/docs/master/rados/operations/add-or-rm-osds/
 #ceph osd create
-ceph osd in ${NODENUM}
-if [ $? -eq 0 ]
-then
-	log failed to create osd.${NODENUM}
-else
-	log OSD osd.${NODENUM}
-fi
+# Looks like we dont need this anyway...
+#ceph osd in ${NODENUM}
+#if [ $? -eq 0 ]
+#then
+#	log failed to create osd.${NODENUM}
+#else
+#	log OSD osd.${NODENUM}
+#fi
 
 ceph-osd -i ${NODENUM} --mkfs --mkkey
 if [ $? -eq 0 ]
@@ -89,7 +93,7 @@ then
 	log ceph-osd ran.
 else
 	log ceph-osd init failed
-	#log `ceph-osd -i ${NODENUM} --mkfs --mkkey`
+	log `ceph-osd -i ${NODENUM} --mkfs --mkkey`
 	exit 5
 fi
 
@@ -99,7 +103,7 @@ then
 	log Keyring modified successfully.
 else
 	log keyring modification failed
-	#log `ceph auth add osd.${NODENUM} osd 'allow *' mon 'allow rwx' -i /var/lib/ceph/osd/ceph-${NODENUM}/keyring`
+	log `ceph auth add osd.${NODENUM} osd 'allow *' mon 'allow rwx' -i /var/lib/ceph/osd/ceph-${NODENUM}/keyring`
 	exit 6
 fi
 
